### ISSUE TITLE
Using multiple nested RxBuilder

### ISSUE THREAD

**Issue by pishguy** [Flutterando/rx_notifier#12]
how can i define multiple nested `RxBuilder` same as for example`RxBuilder2` ?

you suppose i have this widget and used multiple `RxBuilder`

```dart
RxBuilder(
  builder: (_) => _showFunctionalityWidgets.value
      ? RxBuilder(
          builder: (_) =>CInput(
                  controller: _mobileNumber,
                  enabled: enableTextField.value,
                ),
        )
      : const SizedBox(),
),
```

this code better than  it

```dart
RxBuilder2(
  builder: (_v1,v2) => v1.value
      ? CInput(
        controller: _mobileNumber,
        enabled: v2.value,
      ),
      : const SizedBox(),
),
```

**Comment by jacobaraujo7** [comment]
My opinion is that if you need two RxBuilders you may need a bit of componentization.
Since we are using reactive transparent functional programming, there is no need for multiple builders.

I'll close this issue but feel free to open it.
