### ISSUE TITLE
Incompatível com flutter 3.3.10 e anteriores?

### ISSUE THREAD

**Issue by tiagualvs** [Flutterando/rx_notifier#15]
Tentei adicionar o package em um projeto que tenho nesta versão porém não funcionou, fala que o rx_notifier utiliza a versão 1.17.1 de collection porém o flutter_test depende de collection 1.16.0, tentei com dependency_overrides por a nova versão de collection e até que deu exit code 0 no pubspec, mas na hora de usar o package causa erro de element.mount em algum lugar do widget RxRoot e nem builda. então minha dúvida seria se é proposital de ser suportado apenas na stable do flutter (hoje 3.7.10) ou um bug!

**Comment by jacobaraujo7** [comment]
Olá!
É isso mesmo. Infelizmente precisamos de ferramentas da API nova do Dart para poder funcionar. Infelizmente isso tira o suporte para as versões mais antigas.
