### ISSUE TITLE
Version solving failed on channel stable

### ISSUE THREAD

**Issue by RakaAlrian** [Flutterando/rx_notifier#2]
I got this error when adding rx_notifier to my pubspec.yaml file
> The current Dart SDK version is 2.10.4.
> 
> Because counterapp depends on rx_notifier >=0.0.2 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
> pub get failed (1; Because counterapp depends on rx_notifier >=0.0.2 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)

I'm new to flutter, so please correct me if this isn't an issue from this package. I think the error suggest me to change the sdk version to >=2.12.0-0 <3.0.0, so I tried that but then I got another error
> The current Dart SDK version is 2.10.4.
> 
> Because sibene requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
> pub get failed (1; Because sibene requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)

Then, I tried to do flutter upgrade, but it is already up to date on channel stable. I don't really understand about flutter versioning and I never use other channels besides channel stable. Do I need to change my flutter channel to use this package? Or maybe any other suggestions? Thanks

**Comment by jacobaraujo7** [comment]
fixed
