### ISSUE TITLE
Dúvida sobre dispose do rx_notifier

### ISSUE THREAD

**Issue by evandrmb** [Flutterando/rx_notifier#3]
No caso da criação de classe que seja o meu controller com diversos RxNotifiers, como o meu DI vai fazer o dispose deles quando for remover o controller da memória, o flutter_modular por exemplo.

Eu teria que estender de ChangeNotifier o controller e fazer o dispose de cada um no dispose do controller?

**Comment by jacobaraujo7** [comment]
O RxNotifier é uma extensão do ValueNotifier que herda de ChangeNotifier, entáo o dispose acontece automático
