### ISSUE TITLE
Question: Nested RxBuilders

### ISSUE THREAD

**Issue by bobmoff** [Flutterando/rx_notifier#5]
Is it problematic to next RxBuilders in the same Widget tree ?

I get this message: "No Rx variables in that space"

Looks like its when it is trying to untrack, but I am not sure if this break stuff or not.

What happens if I have RxBuilder in the root of the app, how deep will it go to find stuff to track ?

**Comment by jacobaraujo7** [comment]
Hello!
Only what is executed in a functional manner within the scope will be tracked.
This has some implications if using conditionals (if and else) can prevent the object from being seen by tracking.

**Comment by bobmoff** [comment]
Ok. I tried it some more, and I now understand more how it works. Thanks again!
