### ISSUE TITLE
RxCollection object not reactive when using effect

### ISSUE THREAD

**Issue by bobmoff** [Flutterando/rx_notifier#7]
I cant find how your custom collections RxSet etc are tracked when used as a value for a RxNotifier, but It seems to work. But it stops working when I use the effect property on rxObserver. I cant find a reason for this, but it seems consistant.

**Comment by jacobaraujo7** [comment]
You have a exemple?

**Comment by bobmoff** [comment]
Checkout https://github.com/bobmoff/rx_notifier

Made some changes in the example to show the issue, and also added a possible solution in the top of rx_notifier.dart

**Comment by jacobaraujo7** [comment]
Incredible!
What do you think of submitting this correction as a pullrequest here in the project?

**Comment by bobmoff** [comment]
Yes, done!

PR -> #8

By the way, great work with this library. It's my favorite "state manager" 👌🏻

**Comment by jacobaraujo7** [comment]
ACEPTED!
Thank you!
