### ISSUE TITLE
Clear and addAll RxMap without rebuilding N times?

### ISSUE THREAD

**Issue by nhlhelen** [Flutterando/rx_notifier#9]
Hello, is there a way to replace the entire RxMap without calling notifyListeners() N times? The code is as followed: 

```
RxMap<MarkerId, Marker> markers = <MarkerId, Marker>{}.asRx();

if (markerQueue.isNotEmpty) {
      markers.clear();
      markers.addAll(markerQueue.removeAt(0));
}
```

This triggers rebuild many times and affects the performance of my app. Thanks a lot!

**Comment by pishguy** [comment]
+1
